# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
ref:
  # path/to/reference/gDNA.fasta
  sequence:       /secondary/projects/bbc/research/prep_bbc_shared/data/mm10_gencode/sequence/mm10_gencode.fa
  fai:            /secondary/projects/bbc/research/prep_bbc_shared/data/mm10_gencode/sequence/mm10_gencode.fa.fai
  # path/to/STAR/index/directory
  index:          /secondary/projects/bbc/research/prep_bbc_shared/data/mm10_gencode/indexes/star
  # path/to/gtf/file/with/transcripts.gtf
  annotation:     /secondary/projects/bbc/research/prep_bbc_shared/data/mm10_gencode/annotation/mm10_gencode.gtf

scrnaseq_tech: indrop_v2

run_rna_velocity: false

shared_snakemake_repo: "/secondary/projects/bbc/research/shared_snakemake/"
