ref:
  # path/to/reference/gDNA.fasta
  sequence:       /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/dm6_BDGP6.28.100/sequence/dm6_BDGP6.28.100.fa
  fai:            /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/dm6_BDGP6.28.100/sequence/dm6_BDGP6.28.100.fa.fai
  dict:           /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/dm6_BDGP6.28.100/sequence/dm6_BDGP6.28.100.dict
  # path/to/STAR/index/directory
  index:          /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/dm6_BDGP6.28.100/indexes/star
  # path/to/gtf/file/with/transcripts.gtf
  annotation:     /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/dm6_BDGP6.28.100/annotation/dm6_BDGP6.28.100.gtf
  # Known variants for GATK. If providing more than one, separate with a ',' (no spaces).
  known_variants: dgrp2_vcf/dgrp2_dm6.no_chrUn.vcf.gz
  # SNPEff database ID. Ensure that the requested SNPEff database has been prepared.
  snpeff_db_id: 'BDGP6.86'

# Turn on to run trim_galore. Mainly intended for libraries sequenced to a read length longer than the mean fragment size, which can cause mapping issues.
hard_trim:
  run: False
  len: 200 # sets --hardtrim5 in trim_galore, which will "hard-clip sequences from their 3' end" to the read length set here.

# Valid values are 'indrop_v2', '10x_v1', '10x_v2', '10x_v3', 'cellseq192'
scrnaseq_tech: cellseq192

# If True, will ask STARsolo to output the RNA velocity counts in addition to normal gene counts.
run_rna_velocity: True

# If True, will run the GATK RNA-seq variants workflow on the STARSolo BAMs
call_variants: False
call_variant_filtered_cells_only: True # only matters if 'call_variants' is True. If True, then only call variants on the 'filtered' cells from STARsolo.


# Tab-delimited file to rename the final VCF file. Col1 is the old name and col2 is the new name.
# If this file is provided, variant calling will be done only on the samples listed. 
#    Note however that they may still need to be among the 'filtered' set from STARsolo (See 'call_variant_filtered_cells_only' in Snakefile). 
# Note that col1 (old name) is 'samplename.cellbarcode', where sample name comes from the 'sample' column in the samples.tsv
# You may leave this blank if no renaming or subsetting is needed
sample_decoder: ""

# VCF for ASEReadCounter
# Multiallelic variants ignored by ASEReadCounter.
# Variants without heterozygous genotype calls in the VCF are skipped.
run_asereadcounter: False
asereadcounter_vcf: dgrp2_vcf/dgrp2_dm6.no_chrUn.subset.FAKEHETS.vcf.gz

# Packages

bamtools: "bbc2/bamtools/bamtools-2.5.2"
bcftools: "bbc2/bcftools/bcftools-1.17"
fastqc: "bbc2/fastqc/fastqc-0.12.1"
fastq_screen: "bbc2/fastq_screen/fastq_screen-0.14.0"
gatk: "bbc2/gatk/gatk-4.4.0.0"
htslib: "bbc2/htslib/htslib-1.17"
picard: "bbc2/picard/picard-3.0.0"
pigz: "bbc2/pigz/pigz-2.7"
R: "bbc2/R/alt/R-4.2.1-setR_LIBS_USER"
samtools: "bbc2/samtools/samtools-1.17"
SnpEff: "bbc2/SnpEff/SnpEff-5.1"
STAR: "bbc2/STAR/STAR-2.7.11a"
trim_galore: "bbc2/trim_galore/trim_galore-0.6.10"
vt: "bbc2/vt/vt-0.1.16"
