ref:
  # path/to/reference/gDNA.fasta
  sequence:       /secondary/projects/bbc/research/prep_bbc_shared_current/data/dm6_BDGP6.28.100/sequence/dm6_BDGP6.28.100.fa
  fai:            /secondary/projects/bbc/research/prep_bbc_shared_current/data/dm6_BDGP6.28.100/sequence/dm6_BDGP6.28.100.fa.fai
  # path/to/STAR/index/directory
  index:          /secondary/projects/bbc/research/prep_bbc_shared_current/data/dm6_BDGP6.28.100/indexes/star
  # path/to/gtf/file/with/transcripts.gtf
  annotation:     /secondary/projects/bbc/research/prep_bbc_shared_current/data/dm6_BDGP6.28.100/annotation/dm6_BDGP6.28.100.gtf

scrnaseq_tech: cellseq192

run_rna_velocity: true

shared_snakemake_repo: "/secondary/projects/bbc/research/shared_snakemake/"
