ref:
  # path/to/reference/gDNA.fasta
  sequence:       /secondary/projects/bbc/research/prep_bbc_shared_current/data/dm6_BDGP6.28.100/sequence/dm6_BDGP6.28.100.fa
  fai:            /secondary/projects/bbc/research/prep_bbc_shared_current/data/dm6_BDGP6.28.100/sequence/dm6_BDGP6.28.100.fa.fai
  dict:           /secondary/projects/bbc/research/prep_bbc_shared_current/data/dm6_BDGP6.28.100/sequence/dm6_BDGP6.28.100.dict
  # path/to/STAR/index/directory
  index:          /secondary/projects/bbc/research/prep_bbc_shared_current/data/dm6_BDGP6.28.100/indexes/star
  # path/to/gtf/file/with/transcripts.gtf
  annotation:     /secondary/projects/bbc/research/prep_bbc_shared_current/data/dm6_BDGP6.28.100/annotation/dm6_BDGP6.28.100.gtf
  # Known variants for GATK. If providing more than one, separate with a ',' (no spaces).
  known_variants: dgrp2_dm6.no_chrUn.vcf.gz
  # SNPEff database ID. Ensure that the requested SNPEff database has been prepared.
  snpeff_db_id: 'BDGP6.86'

# Valid values are 'indrop_v2', '10x_v1', '10x_v2', '10x_v3', 'cellseq192'
scrnaseq_tech: cellseq192

# If True, will ask STARsolo to output the RNA velocity counts in addition to normal gene counts.
run_rna_velocity: True

# If True, will run the GATK RNA-seq variants workflow on the STARSolo BAMs
call_variants: True

# Tab-delimited file to rename the final VCF file. Col1 is the old name and col2 is the new name.
# Note that the 'old name' will be 'samplename.cellbarcode', where sample name comes from the 'sample' column in the samples.tsv
# You may leave this blank if no renaming is needed
sample_decoder: "vcf_reheader.tsv"
