ref:
  # path/to/reference/gDNA.fasta
  sequence:       /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/dm6_BDGP6.28.100/sequence/dm6_BDGP6.28.100.fa
  fai:            /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/dm6_BDGP6.28.100/sequence/dm6_BDGP6.28.100.fa.fai
  dict:           /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/dm6_BDGP6.28.100/sequence/dm6_BDGP6.28.100.dict
  # path/to/STAR/index/directory
  index:          /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/dm6_BDGP6.28.100/indexes/star
  # path/to/gtf/file/with/transcripts.gtf
  annotation:     /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/dm6_BDGP6.28.100/annotation/dm6_BDGP6.28.100.gtf
  # Known variants for GATK. If providing more than one, separate with a ',' (no spaces).
  known_variants: dgrp2_vcf/dgrp2_dm6.no_chrUn.vcf.gz
  # SNPEff database ID. Ensure that the requested SNPEff database has been prepared.
  snpeff_db_id: 'BDGP6.86'

# Valid values are 'indrop_v2', '10x_v1', '10x_v2', '10x_v3', 'cellseq192'
scrnaseq_tech: cellseq192

# If True, will ask STARsolo to output the RNA velocity counts in addition to normal gene counts.
run_rna_velocity: True

# If True, will run the GATK RNA-seq variants workflow on the STARSolo BAMs
call_variants: True
call_variant_filtered_cells_only: True # only matters if 'call_variants' is True. If True, then only call variants on the 'filtered' cells from STARsolo.


# Tab-delimited file to rename the final VCF file. Col1 is the old name and col2 is the new name.
# If this file is provided, variant calling will be done only on the samples listed. 
#    Note however that they may still need to be among the 'filtered' set from STARsolo (See 'call_variant_filtered_cells_only' in Snakefile). 
# Note that col1 (old name) is 'samplename.cellbarcode', where sample name comes from the 'sample' column in the samples.tsv
# You may leave this blank if no renaming or subsetting is needed
sample_decoder: ""

# VCF for ASEReadCounter
# Multiallelic variants ignored by ASEReadCounter.
# Variants without heterozygous genotype calls in the VCF are skipped.
asereadcounter_vcf: dgrp2_vcf/dgrp2_dm6.no_chrUn.subset.FAKEHETS.vcf.gz

# Packages

bamtools: "bbc/bamtools/bamtools-2.5.1"
bcftools: "bbc/bcftools/bcftools-1.12"
fastqc: "bbc/fastqc/fastqc-0.11.9"
fastq_screen: "bbc/fastq_screen/fastq_screen-0.14.0"
gatk: "bbc/gatk/gatk-4.1.8.1"
htslib: "bbc/htslib/htslib-1.10.2"
picard: "bbc/picard/picard-2.23.3"
pigz: "bbc/pigz/pigz-2.4"
R: "bbc/R/R-4.0.2-setR_LIBS_USER"
samtools: "bbc/samtools/samtools-1.12"
SnpEff: "bbc/SnpEff/SnpEff-4.3t"
STAR: "bbc/STAR/STAR-2.7.8a"
vt: "bbc/vt/vt-0.1.16"
