$schema: "http://json-schema.org/draft-06/schema#"

description: config file.

type: object

properties:
  ref:
    type: object
    properties:
      index:
        type: string
      annotation:
        type: string
    required:
      - index
      - annotation

  scrnaseq_tech:
    type: string
    enum:
      - indrop_v2
      - 10x_v1
      - 10x_v2
      - 10x_v3
      - cellseq192
